version: '3.9'

services:
  gpu_node_exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:3.1.8-3.1.5-ubuntu20.04
    container_name: svr_gpu_node_exporter
    restart: unless-stopped
    ports:
      - 9400:9400
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
