version: '3.9'

volumes:
  svr_prometheus_data:
    external: true
  svr_grafana_data:
    external: true

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: svr_monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - svr_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.1.5
    container_name: svr_monitoring_grafana
    restart: unless-stopped
    volumes:
      - svr_grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/rabbitmq.yaml
      - ./grafana/dashboards:/dashboards
    environment:  
      - GF_LOG_LEVEL="warning"
    ports:
      - 3000:3000

