global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['185.17.0.157:15692']

  - job_name: redis_exporter
    static_configs:
    - targets: ['185.17.0.157:9121']
