global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['0.0.0.0:9100']
        labels:
          instance: 'search_engine'
      - targets: ['0.0.0.0:9100']
        labels:
          instance: 'ml_processing'

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['0.0.0.0:15692']

  - job_name: 'redis_exporter'
    static_configs:
    - targets: ['0.0.0.0:9121']
