global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'node'
  static_configs:
  - targets: ['0.0.0.0:9100']
    labels:
      instance: 'device'
  - targets: ['0.0.0.0:9100']
    labels:
      instance: 'device_with_gpu'

- job_name: 'gpu-metrics'
  static_configs:
  - targets: ['0.0.0.0:9400']
    labels:
      instance: 'device_with_gpu'

- job_name: 'rabbitmq'
  static_configs:
  - targets: ['0.0.0.0:15692']

- job_name: 'redis_exporter'
  static_configs:
  - targets: ['0.0.0.0:9121']

- job_name: 'ml_processing'
  honor_labels: true
  static_configs:
  - targets: ['0.0.0.0:9090']
